export * from './PatientRegistration/InformationGroup';
export * from './PatientRegistration/patient-manager.screen';
export * from './PatientRegistration/patient-order.screen';
export * from './PatientRegistration/PatientRegistration';
export * from './PatientRegistration/patient-result.screen';
export * from './PatientRegistration/patient-sample.screen';
export * from './PatientRegistration/patient-test.screen';
export * from './PatientRegistration/patient-visit.screen';
export * from './PatientRegistration/SpecialResult';
