version: '3.8'

services:
  app:
    container_name: limsplus-portal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app
    env_file:
      - .env
    ports:
      - 3000:3000
