version: '0.0.1'

services:
  app:
    container_name: limsplus-portal
    image: limsplus-portal
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
