version: '3.8'

services:
  app:
    container_name: limsplus-portal
    # image: limsplus-portal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/web
    ports:
      - 3000:3000
