version: '3.8'
services:
  # Portal
  mongo:
    build:
      context: .
      dockerfile: DockerfileDB
    ports:
      - 2717:27017
    networks:
      - limsplus_newtwork
    volumes:
      - limplus:/data/db
  api:
    image: onlyappasaheb4/limsplus_service:latest
    ports:
      - 8080:8080
    networks:
      - limsplus_newtwork
    depends_on:
      - mongo
  app:
    image: onlyappasaheb4/limsplus_portal:latest
    ports:
      - 3000:3000
    networks:
      - limsplus_newtwork
networks:
  limsplus_newtwork:
    driver: bridge
volumes:
  limplus:
    driver: local
