export interface CorporateClients {
  _id?: string
  duplicateId?: string
  dateCreation?: number
  dateActiveFrom?: number
  dateActiveTo?: number
  version?: number
  keyNum?: string
  enteredBy?: string
  corporateCode?: string
  corporateName?: string
  invoiceAc?: string
  priceList?: string
  priceGroup?: string
  billingOn?: string
  address?: string
  city?: string
  state?: string
  country?: string
  postcode?: number
  customerGroup?: string
  category?: string
  confidential?: boolean
  telephone?: string
  mobileNo?: string
  email?: string   
  deliveryType?: string
  deliveryMethod?: string
  salesTerritoRy?: string
  area?: string
  zone?: string
  edi?: string
  ediAddress?: string
  urgent?: boolean
  schedule?: string
  reportFormat?: string
  info?: string
  fyiLine?: string
  workLine?: string
  status?: string
}
