export class PendingPanelApproval {
  _id: string;
  pId: number;
  name: string;
  age: string;
  sex: string;
  dob: Date;
  patientMobileNo: string;
  doctorId: string;
  doctorMobileNo: number;
  registrationLocation: string;
  contactNo: string;
  history: boolean;
  historyDetails: string;
  labId: number;
  sampleId: number;
  sampleType: string;
  containerId: string;
  panel: string;
  dueDate: Date;
  status: string;
  comments: string;
  pLab: string;
  department: string;
  test: string;
  analyte: string;
  result: string;
  final: string;
  abnFlag: boolean;
  critical: boolean;
  units: string;
  refRanges: JSON;
  remarks: string;
  deltaFlag: boolean;
  deltaValue: string;
  resultStatus: string;
  testStatus: string;
  approvalDate: Date;
  approvalStatus: string;
  autoRelease: boolean;
  patientOrderId: string;
  reportPriority: string;
  enteredBy: string;
  documentType: string;
  dateOfEntry: Date;
  lastUpdated: Date;

  constructor(rawData: {[key in string]: any}) {
    this._id = rawData._id;
    this.pId = rawData.pId;
    this.name = rawData.name;
    this.age = rawData.age;
    this.sex = rawData.sex;
    this.dob = rawData.dob;
    this.patientMobileNo = rawData.patientMobileNo;
    this.doctorId = rawData.doctorId;
    this.doctorMobileNo = rawData.doctorMobileNo;
    this.registrationLocation = rawData.registrationLocation;
    this.contactNo = rawData.contactNo;
    this.history = rawData.history;
    this.historyDetails = rawData.historyDetails;
    this.labId = rawData.labId;
    this.sampleId = rawData.sampleId;
    this.sampleType = rawData.sampleType;
    this.containerId = rawData.containerId;
    this.panel = rawData.panel;
    this.dueDate = rawData.dueDate;
    this.status = rawData.status;
    this.comments = rawData.comments;
    this.pLab = rawData.pLab;
    this.department = rawData.department;
    this.test = rawData.test;
    this.analyte = rawData.analyte;
    this.result = rawData.result;
    this.final = rawData.final;
    this.abnFlag = rawData.abnFlag;
    this.critical = rawData.critical;
    this.units = rawData.units;
    this.refRanges = rawData.refRanges;
    this.remarks = rawData.remarks;
    this.deltaFlag = rawData.deltaFlag;
    this.deltaValue = rawData.deltaValue;
    this.resultStatus = rawData.resultStatus;
    this.testStatus = rawData.testStatus;
    this.approvalDate = rawData.approvalDate;
    this.approvalStatus = rawData.approvalStatus;
    this.autoRelease = rawData.autoRelease;
    this.patientOrderId = rawData.patientOrderId;
    this.reportPriority = rawData.reportPriority;
    this.enteredBy = rawData.enteredBy;
    this.documentType = rawData.documentType;
    this.dateOfEntry = rawData.dateOfEntry;
    this.lastUpdated = rawData.lastUpdated;
  }
}
