export const options = {
  equipmentType: [{ title: "ERP" }, { title: "HORIBA" }],
  submitter_submitter: [{ title: "Host > LIS" }, { title: "LIS > Host" }],
  data_type: [{ title: "HL7" }, { title: "ASTM" }, { title: "HEX" }],
  segments: [
    { title: "MSH" },
    { title: "PID" },
    { title: "ORC" },
    { title: "OBR" },
    { title: "H" },
    { title: "P" },
    { title: "O" },
    { title: "R" },
    { title: "C" },
    { title: "Q" },
    { title: "M" },
    { title: "L" },
  ],
  segment_usage: [{ title: "Required" }, { title: "Optional" }],
}
