export class TransactionHeader {
  _id: string;
  rLab: string;
  headerId: number;
  collectionCenter: string;
  corporateCode: string;
  labId: string;
  invoiceAc: number;
  invoiceDate: Date;
  actionDate: Date;
  registrationDate: Date;
  dueDate: Date;
  reportingDate: Date;
  doctorId: number;
  pId: number;
  priceList: string;
  grossAmount: number;
  netAmount: number;
  discount: number;
  receivedAmount: number;
  balance: number;
  acClass: string;
  accountType: string;
  customerName: string;
  customerGroup: string;
  allMiscCharges: Array<any>;
  discountCharges: object;
  status: string;
  enteredBy: string;
  documentType: string;
  dateOfEntry: Date;
  lastUpdated: Date;

  constructor(rawData: {[key in string]: any}) {
    this._id = rawData._id;
    this.rLab = rawData.rLab;
    this.headerId = rawData.headerId;
    this.collectionCenter = rawData.collectionCenter;
    this.corporateCode = rawData.corporateCode;
    this.labId = rawData.labId;
    this.invoiceAc = rawData.invoiceAc;
    this.invoiceDate = rawData.invoiceDate;
    this.actionDate = rawData.actionDate;
    this.registrationDate = rawData.registrationDate;
    this.dueDate = rawData.dueDate;
    this.reportingDate = rawData.reportingDate;
    this.doctorId = rawData.doctorId;
    this.pId = rawData.pId;
    this.priceList = rawData.priceList;
    this.grossAmount = rawData.grossAmount;
    this.netAmount = rawData.netAmount;
    this.discount = rawData.discount;
    this.receivedAmount = rawData.receivedAmount;
    this.balance = rawData.balance;
    this.acClass = rawData.acClass;
    this.accountType = rawData.accountType;
    this.customerGroup = rawData.customerGroup;
    this.customerName = rawData.customerName;
    this.allMiscCharges = rawData.allMiscCharges;
    this.discountCharges = rawData.discountCharges;
    this.status = rawData.status;
    this.enteredBy = rawData.enteredBy;
    this.documentType = rawData.documentType;
    this.dateOfEntry = rawData.dateOfEntry;
    this.lastUpdated = rawData.lastUpdated;
  }
}
