export interface RegistrationLocations {
  _id?: string
  duplicateId?: string  
  dateCreation?: number
  dateActiveFrom?: number
  dateActiveTo?: number
  version?: number
  keyNum?: string
  enteredBy?: string
  locationCode?: string
  locationName?: string
  address?: string
  city?: string
  state?: string
  country?: string
  postcode?: number
  customerGroup?: string
  category?: string
  confidential?: boolean
  telephone?: string
  mobileNo?: string
  email?: string
  deliveryType?: string
  deliveryMethod?: string
  corporateCode?: string
  invoiceAc?: string
  labLicence?: string
  printLabel?: boolean
  methodColn?: string
  workHrs?: number
  salesTerritoRy?: string
  area?: string
  zone?: string
  route?: string
  lab?: string
  location?: string
  neverBill?: boolean
  edi?: string
  ediAddress?: string
  urgent?: boolean
  schedule?: string
  reportFormat?: string
  info?: string
  fyiLine?: string
  workLine?: string
  status?: string
}
