export class Company {
  _id: string;
  code: string;
  name: string;
  description: string;
  module: string;
  admin: string;
  password: string;
  postalCode: number;
  country: string;
  state: string;
  district: string;
  city: string;
  area: string;
  address: string;
  mobileNo: string;
  contactNo: string;
  email: string;
  web: string;
  webPortal: string;
  registeredOffice: string;
  corporateOffice: string;
  customerCare: string;
  gst: string;
  sacCode: string;
  cinNo: string;
  companyLogo: any;
  friLine: string;
  workLine: string;
  dateCreation: Date;
  dateActive: Date;
  dateExpire: Date;
  enteredBy: string;
  status: string;
  environment: string;
  dateOfEntry: Date;
  lastUpdated: Date;
  constructor(rawData: { [key in string]: any }) {
    this._id = rawData._id;
    this.code = rawData.code;
    this.name = rawData.name;
    this.description = rawData.description;
    this.module = rawData.module;
    this.admin = rawData.admin;
    this.password = rawData.password;
    this.postalCode = rawData.postalCode;
    this.country = rawData.country;
    this.state = rawData.state;
    this.district = rawData.district;
    this.city = rawData.city;
    this.area = rawData.area;
    this.address = rawData.address;
    this.mobileNo = rawData.mobileNo;
    this.contactNo = rawData.contactNo;
    this.email = rawData.email;
    this.web = rawData.web;
    this.webPortal = rawData.webPortal;
    this.registeredOffice = rawData.registeredOffice;
    this.corporateOffice = rawData.corporateOffice;
    this.customerCare = rawData.customerCare;
    this.gst = rawData.gst;
    this.sacCode = rawData.sacCode;
    this.cinNo = rawData.cinNo;
    this.friLine = rawData.friLine;
    this.workLine = rawData.workLine;
    this.dateCreation = rawData.dateCreation;
    this.dateActive = rawData.dateActive;
    this.dateExpire = rawData.dateExpire;
    this.enteredBy = rawData.enteredBy;
    this.status = rawData.status;
    this.environment = rawData.environment;
    this.dateOfEntry = rawData.dateOfEntry;
    this.lastUpdated = rawData.lastUpdated;
  }
}
